language: node_js
node_js:
  - "8"

install:
  - npm install

script:
  - truffle test

before_script:
  - testrpc > /dev/null &
  - sleep 5

after_script:
  - "travis_wait 30 sleep 1800 &"
  - npm run test:coverage
